#!/usr/bin/env zsh
DIR=${0:a:h}
STORE="$DIR/store"

echo "Applying the $STORE..."
while read file
do
	echo "Applying $file..."
	if [[ -d $file ]]; then
		mkdir -p $file
		cp -r $STORE/$file/. $file/
	elif [[ -f $file ]]; then
		mkdir -p `dirname $file`
		cp -r $STORE/$file $file
		echo "";
	fi;
done < "$DIR/store.lst"
