#!/bin/zsh
DIR=${0:a:h}
STORE="$DIR/store"

echo "Clearing the $STORE..."
rm -r "$STORE"
mkdir "$STORE"

echo "Updating the $STORE..."
while read file
do
	echo "Copying $file..."
	if [[ -d $file ]]; then
		mkdir -p $STORE/$file
		cp -r $file/. $STORE/$file/
	elif [[ -f $file ]]; then
		mkdir -p $STORE/`dirname $file`
		cp -r $file $STORE/$file
		echo "";
	fi;
done < "$DIR/store.lst"
